# Generated by Django 5.2.1 on 2025-05-22 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='オーナー名')),
                ('contact_info', models.JSONField(blank=True, null=True, verbose_name='連絡先情報')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('assigned_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='担当営業')),
            ],
            options={
                'verbose_name': 'オーナー',
                'verbose_name_plural': 'オーナー',
            },
        ),
    ]
