# Generated by Django 5.2.1 on 2025-05-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会社名')),
                ('contact_info', models.JSONField(blank=True, null=True, verbose_name='連絡先情報')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '不動産会社/管理会社',
                'verbose_name_plural': '不動産会社/管理会社',
            },
        ),
    ]
