# Generated by Django 5.2.1 on 2025-05-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('property_type', models.CharField(choices=[('Apartment', '集合住宅'), ('House', '戸建て')], max_length=50, verbose_name='物件種別')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='築年数')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='最終点検/工事日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to='api.company', verbose_name='管理会社')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.owner', verbose_name='オーナー')),
            ],
            options={
                'verbose_name': '物件',
                'verbose_name_plural': '物件',
            },
        ),
    ]
