# Generated by Django 5.2.1 on 2025-05-22 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_constructiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('New', '新規'), ('CS', 'CS')], max_length=50, verbose_name='案件種別')),
                ('status', models.CharField(choices=[('Appointment', 'アポ取得済'), ('Surveyed', '調査/点検済'), ('Negotiating', '商談中'), ('Contracted', '契約済'), ('InProgress', '施工中'), ('Completed', '完了'), ('Cancelled', '中止')], default='Appointment', max_length=50, verbose_name='案件ステータス')),
                ('occurence_date', models.DateField(verbose_name='発生日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('assigned_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='担当営業')),
                ('expected_construction_types', models.ManyToManyField(related_name='cases', to='api.constructiontype', verbose_name='想定工事種別')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.owner', verbose_name='オーナー')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.property', verbose_name='物件')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
            },
        ),
    ]
