# Generated by Django 5.2.1 on 2025-05-22 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='合計金額')),
                ('approval_status', models.CharField(choices=[('Pending', '未承認'), ('Approved', '承認済'), ('Rejected', '却下')], default='Pending', max_length=50, verbose_name='承認ステータス')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='承認日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_estimates', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='api.case', verbose_name='案件')),
            ],
            options={
                'verbose_name': '見積書',
                'verbose_name_plural': '見積書',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='項目名')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小計')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.estimate', verbose_name='見積書')),
            ],
            options={
                'verbose_name': '見積明細',
                'verbose_name_plural': '見積明細',
            },
        ),
    ]
