# Generated by Django 5.2.1 on 2025-05-22 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_estimate_estimateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('Order', '注文書'), ('Contract', '契約書'), ('CompletionConfirmation', '契約兼完了確認書')], max_length=50, verbose_name='契約書種別')),
                ('contract_date', models.DateField(verbose_name='契約日')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='契約金額')),
                ('desired_construction_date', models.DateField(blank=True, null=True, verbose_name='施工希望日')),
                ('payment_terms', models.TextField(blank=True, null=True, verbose_name='支払い条件')),
                ('owner_sign_date', models.DateField(blank=True, null=True, verbose_name='オーナー記入日')),
                ('approval_status', models.CharField(choices=[('Pending', '未承認'), ('Approved', '承認済'), ('Rejected', '却下')], default='Pending', max_length=50, verbose_name='承認ステータス (本部チェック)')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='承認日')),
                ('customer_confirmation_status', models.CharField(choices=[('Required', '要'), ('NotRequired', '不要'), ('NotImplemented', '未実施'), ('CompletedOK', '実施済OK'), ('CompletedNG', '実施済NG')], default='Required', max_length=50, verbose_name='お客様確認ステータス')),
                ('customer_confirmation_date', models.DateField(blank=True, null=True, verbose_name='お客様確認日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.case', verbose_name='案件')),
                ('customer_confirmation_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='お客様確認担当者')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='api.estimate', verbose_name='関連見積書')),
            ],
            options={
                'verbose_name': '契約書',
                'verbose_name_plural': '契約書',
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='項目名')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小計')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.contract', verbose_name='契約書')),
            ],
            options={
                'verbose_name': '契約明細',
                'verbose_name_plural': '契約明細',
            },
        ),
    ]
