# Generated by Django 5.2.1 on 2025-05-22 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_contract_contractitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField(verbose_name='調査/点検日')),
                ('summary', models.TextField(verbose_name='概要')),
                ('details', models.TextField(verbose_name='結果詳細')),
                ('attachment_paths', models.JSONField(blank=True, null=True, verbose_name='添付資料パス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_records', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_records', to='api.case', verbose_name='案件')),
            ],
            options={
                'verbose_name': '調査/点検記録',
                'verbose_name_plural': '調査/点検記録',
            },
        ),
    ]
