# Generated by Django 5.2.1 on 2025-05-22 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_surveyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='報告/商談日')),
                ('negotiation_content', models.TextField(verbose_name='商談内容')),
                ('result', models.CharField(choices=[('Won', '受注'), ('Lost', '失注'), ('Ongoing', '継続')], max_length=50, verbose_name='結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_records', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_records', to='api.case', verbose_name='案件')),
            ],
            options={
                'verbose_name': '報告/商談記録',
                'verbose_name_plural': '報告/商談記録',
            },
        ),
    ]
