# Generated by Django 5.2.1 on 2025-05-22 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reportrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='スケジュール日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時間')),
                ('type', models.CharField(choices=[('Appointment', 'アポイント'), ('Construction', '施工')], max_length=50, verbose_name='種別')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='場所')),
                ('details', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='api.case', verbose_name='関連案件')),
            ],
            options={
                'verbose_name': 'スケジュール',
                'verbose_name_plural': 'スケジュール',
            },
        ),
    ]
