# Generated by Django 5.2.1 on 2025-05-22 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAlliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('referral_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='紹介手数料率')),
                ('contract_info', models.TextField(blank=True, null=True, verbose_name='契約書情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alliances', to='api.company', verbose_name='提携会社')),
            ],
            options={
                'verbose_name': '業務提携',
                'verbose_name_plural': '業務提携',
            },
        ),
    ]
