# Generated by Django 5.2.1 on 2025-05-23 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_estimatehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='バージョン番号')),
                ('data', models.JSONField(verbose_name='契約書データスナップショット')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_histories', to=settings.AUTH_USER_MODEL, verbose_name='変更者')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.contract', verbose_name='元契約書')),
            ],
            options={
                'verbose_name': '契約書履歴',
                'verbose_name_plural': '契約書履歴',
                'ordering': ['-changed_at'],
            },
        ),
    ]
