# Generated by Django 5.2.1 on 2025-05-23 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contracthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsbestosSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField(verbose_name='調査日')),
                ('result', models.CharField(max_length=255, verbose_name='調査結果')),
                ('attachments', models.JSONField(blank=True, null=True, verbose_name='添付ファイルパス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asbestos_surveys', to='api.case', verbose_name='関連案件')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asbestos_surveys', to='api.contract', verbose_name='関連契約書')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asbestos_surveys', to=settings.AUTH_USER_MODEL, verbose_name='調査担当者')),
            ],
            options={
                'verbose_name': '石綿調査書類',
                'verbose_name_plural': '石綿調査書類',
                'ordering': ['-survey_date', '-created_at'],
            },
        ),
    ]
