# Generated by Django 5.2.1 on 2025-05-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_asbestossurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='売上金額')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='原価金額')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='紹介手数料')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_costs', to='api.case', verbose_name='関連案件')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_costs', to='api.contract', verbose_name='関連契約書')),
            ],
            options={
                'verbose_name': '売上・原価管理',
                'verbose_name_plural': '売上・原価管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
