# Generated by Django 5.2.1 on 2025-05-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_revenuecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作種別')),
                ('model', models.CharField(max_length=100, verbose_name='対象モデル')),
                ('object_id', models.CharField(max_length=100, verbose_name='対象ID')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ',
                'ordering': ['-created_at'],
            },
        ),
    ]
