# Generated by Django 5.2.1 on 2025-05-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='タイトル'),
        ),
    ]
